export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as FeaturedProducts } from './featuredProducts/FeaturedProducts'
export { default as Card } from './card/Card'
export { default as Category } from './category/Category'
export { default as ProductList} from './productList/ProductList'